src/Entity/MateriaLoadout.php
<?php

namespace App\Entity;

use App\Repository\MateriaLoadoutRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Serializer\Annotation\Ignore;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=MateriaLoadoutRepository::class)
 */
class MateriaLoadout {
	/**
	 * @ORM\Id()
	 * @ORM\GeneratedValue()
	 * @ORM\Column(type="integer")
	 * @Groups({"view", "tree"})
	 */
	private $id;

	/**
	 * @ORM\Column(type="string", length=255)
	 * @Assert\NotBlank()
	 * @Groups({"view", "tree"})
	 */
	private $name;

	/**
	 * @ORM\ManyToOne(targetEntity=User::class, inversedBy="materiaLoadouts")
	 * @ORM\JoinColumn(nullable=false)
	 * @Ignore()
	 */
	private $owner;

	/**
	 * @ORM\OneToMany(targetEntity=MateriaLoadoutItem::class, mappedBy="loadout", orphanRemoval=true, cascade={"persist", "remove"})
	 * @Groups({"view"})
	 */
	private $items;

	/**
	 * @ORM\ManyToOne(targetEntity=MateriaLoadout::class, inversedBy="children")
	 * @Ignore()
	 */
	private $parent;

	/**
	 * @ORM\OneToMany(targetEntity=MateriaLoadout::class, mappedBy="parent", orphanRemoval=true, cascade={"persist", "remove"})
	 * @Ignore()
	 */
	private $children;

	/**
	 * @ORM\Column(type="json")
	 * @Groups({"view"})
	 */
	private $partyOrder = ['c', 'b', 't', 'a'];

	/**
	 * @ORM\Column(type="text", nullable=true)
	 */
	private $preferredChangeKey;

	/**
	 * @ORM\Column(type="string", length=2, nullable=true)
	 */
	private $startCharacter;

	/**
	 * @ORM\Column(type="text", nullable=true)
	 * @Groups({"notes"})
	 */
	private $notes;

	public function __construct() {
		$this->children = new ArrayCollection();
		$this->items    = new ArrayCollection();

		foreach (['c', 't', 'b', 'a'] as $char) {
			for ($row = 0; $row <= 1; $row++) {
				for ($col = 0; $col < ($row === 0 ? 7 : 4); $col++) {
					$i = new MateriaLoadoutItem();
					$i
						->setCharName($char)
						->setRow($row)
						->setCol($col);

					$this->addItem($i);
				}
			}
		}
	}

	public function getId(): ?int {
		return $this->id;
	}

	public function getName(): ?string {
		return $this->name;
	}

	public function setName(string $name): self {
		$this->name = $name;

		return $this;
	}

	/**
	 * @return Collection|MateriaLoadoutItem[]
	 */
	public function getItems(): Collection {
		return $this->items;
	}

	public function addItem(MateriaLoadoutItem $item): self {
		if (!$this->items->contains($item)) {
			$this->items[] = $item;
			$item->setLoadout($this);
		}

		return $this;
	}

	public function removeItem(MateriaLoadoutItem $item): self {
		if ($this->items->contains($item)) {
			$this->items->removeElement($item);
			// set the owning side to null (unless already changed)
			if ($item->getLoadout() === $this) {
				$item->setLoadout(null);
			}
		}

		return $this;
	}

	/**
	 * @return $this
	 */
	public function getRoot() {
		$c = $this;
		while ($c->getParent() !== null) {
			$c = $c->getParent();
		}

		return $c;
	}

	public function getOwner(): ?User {
		return $this->owner;
	}

	public function setOwner(?User $owner): self {
		$this->owner = $owner;

		return $this;
	}

	public function getParent(): ?self {
		return $this->parent;
	}

	public function setParent(?self $parent): self {
		$this->parent = $parent;

		return $this;
	}

	/**
	 * @return Collection|self[]
	 */
	public function getChildren(): Collection {
		return $this->children;
	}

	public function addChild(self $child): self {
		if (!$this->children->contains($child)) {
			$this->children[] = $child;
			$child->setParent($this);
		}

		return $this;
	}

	public function removeChild(self $child): self {
		if ($this->children->contains($child)) {
			$this->children->removeElement($child);
			// set the owning side to null (unless already changed)
			if ($child->getParent() === $this) {
				$child->setParent(null);
			}
		}

		return $this;
	}

	public function getPartyOrder(): ?array {
		return $this->partyOrder;
	}

	public function setPartyOrder(array $partyOrder): self {
		$this->partyOrder = $partyOrder;

		return $this;
	}

	public function getPreferredChangeKey(): ?string {
		return $this->preferredChangeKey;
	}

	public function setPreferredChangeKey(?string $preferredChangeKey): self {
		$this->preferredChangeKey = $preferredChangeKey;

		return $this;
	}

	public function getStartCharacter(): ?string {
		return $this->startCharacter;
	}

	public function setStartCharacter(?string $startCharacter): self {
		$this->startCharacter = $startCharacter;

		return $this;
	}

	public function getNotes(): ?string {
		return $this->notes;
	}

	public function setNotes(?string $notes): self {
		$this->notes = $notes;

		return $this;
	}
}

src/Controller/DefaultController.php
<?php

namespace App\Controller;

use App\Entity\MateriaLoadout;
use App\Form\DocumentType;
use App\Form\MateriaLoadoutType;
use App\Service\LoadoutHelper;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\FormFactoryInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\NotBlank;

class DefaultController extends AbstractController {
	private EntityManagerInterface $em;
	private LoadoutHelper $lh;

	public function __construct(EntityManagerInterface $em, LoadoutHelper $lh) {
		$this->em = $em;
		$this->lh = $lh;
	}

	/**
	 * @Route("/", name="default_index")
	 */
	public function index(Request $request) {
		$loadouts = $this->em->getRepository(MateriaLoadout::class)
			->findBy(['owner' => $this->getUser()]);

		$form = $this->createFormBuilder()->getForm();
		$form->handleRequest($request);

		if ($form->isSubmitted() && $form->isValid()) {
			$loadout = $this->lh->addDemoLoadoutToUser($this->getUser());
			$this->addFlash('success', 'Demo loadout added to your account.');

			return $this->redirectToRoute('default_view_loadout', ['loadout' => $loadout->getId()]);
		}

		return $this->render('default/index.html.twig', [
			'loadouts' => $loadouts,
			'demoform' => $form->createView()
		]);
	}

	/**
	 * @Route("/add", name="default_add_loadout")
	 * @Route("/edit/{loadout}", name="default_edit_loadout")
	 * @Security("is_granted('ROLE_USER') && (null == loadout || is_granted('LOADOUT_EDIT', loadout))")
	 */
	public function add(Request $request, MateriaLoadout $loadout = null) {
		if (null === $loadout) {
			$loadout = new MateriaLoadout();
			$loadout
				->setOwner($this->getUser());
		}

		$form = $this->createForm(MateriaLoadoutType::class, $loadout);

		$form->handleRequest($request);
		if ($form->isSubmitted() && $form->isValid()) {
			$this->em->persist($loadout);
			$this->em->flush();

			return $this->redirectToRoute('default_view_loadout', ['loadout' => $loadout->getId()]);
		}

		return $this->render('default/add.html.twig', [
			'form' => $form->createView()
		]);
	}

	/**
	 * @Route("/view/{loadout}", name="default_view_loadout")
	 * @IsGranted("ROLE_USER")
	 * @IsGranted("LOADOUT_VIEW", subject="loadout")
	 */
	public function view(MateriaLoadout $loadout, Request $request, FormFactoryInterface $ffi) {
		$cloneForm = $ffi->createNamedBuilder('clone')->getForm();

		$cloneForm->handleRequest($request);
		if ($cloneForm->isSubmitted() && $cloneForm->isValid()) {
			$new = $this->lh->createNewLoadoutFrom($loadout);

			$this->addFlash('success', 'Created new loadout from parent.');

			return $this->redirectToRoute('default_edit_loadout', ['loadout' => $new->getId()]);
		}

		return $this->render('default/view.html.twig', [
			'loadout' => $loadout,
			'clone'   => $cloneForm->createView()
		]);
	}

	/**
	 * @Route("/delete/{loadout}", name="default_delete_loadout")
	 * @IsGranted("ROLE_USER")
	 * @IsGranted("LOADOUT_DELETE", subject="loadout")
	 */
	public function delete(MateriaLoadout $loadout, Request $request) {
		$deleteForm = $this->createFormBuilder()
			->add('checkbox', CheckboxType::class, [
				'label'       => 'I understand this action cannot be undone.',
				'required'    => true,
				'constraints' => [
					new NotBlank()
				]
			]);

		$deleteForm = $deleteForm->getForm();
		$deleteForm->handleRequest($request);

		if ($deleteForm->isSubmitted() && $deleteForm->isValid()) {
			$this->em->remove($loadout);
			$this->em->flush();

			$this->addFlash('warning', sprintf('Deleted loadout \'%s\'.', $loadout->getName()));

			return $this->redirectToRoute('default_index');
		}

		$children = [];
		foreach($loadout->getChildren() as $child) {
			$this->lh->getLeveledChildren($child, $children);
		}

		return $this->render('default/delete.html.twig', [
			'loadout'  => $loadout,
			'children' => $children,
			'form'     => $deleteForm->createView()
		]);
	}

	/**
	 * @Route("/auto/{loadout}", name="default_auto_loadout")
	 * @IsGranted("ROLE_USER")
	 * @IsGranted("LOADOUT_EDIT", subject="loadout")
	 */
	public function auto(MateriaLoadout $loadout) {
		$children = [];
		foreach($loadout->getChildren() as $child) {
			$this->lh->getLeveledChildren($child, $children);
		}

		return $this->render('default/auto.html.twig', [
			'loadout' => $loadout
		]);
	}

	/**
	 * @Route("/login", name="default_login")
	 */
	public function auth() {
		$this->denyAccessUnlessGranted('ROLE_USER');

		return $this->redirectToRoute('default_index');
	}
}

templates/default/add.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<div class="container">
		{{ form_start(form) }}
		{{ form_errors(form) }}
		{{ form_rest(form) }}
		<div>
			<button type="submit" class="btn btn-primary">Submit</button>
		</div>
		{{ form_end(form) }}
	</div>
{% endblock %}

templates/default/auto.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<div class="container">
		<div class="row">
			<div class="col">
				<div class="alert alert-warning">
					<i class="fas fa-exclamation-triangle"></i>
					This is really beta and might break/not output the best changes/etc. Please double-check that the end result is correct and what you expect!
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col">
				<div id="display" data-id="{{ loadout.id }}"></div>
			</div>
		</div>
	</div>

	<meta name="materia-preference" content="{{ app.user.materiaCoordinatesPreference }}" />
{% endblock %}

{% block javascripts %}
	{{ parent() }}
	{{ encore_entry_script_tags('table') }}
{% endblock %}

templates/default/delete.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<div class="container">
		<div class="row">
			<div class="col">
				<div class="alert alert-danger">
						{% if children|length >0 %}
							The loadout <b>{{ loadout.name }}</b> and the following children will be deleted permanently:<br />
							{% for level, childs in children %}
								{% for child in childs %}
									{% for _ in 0..level %}
										<span>&nbsp;</span>
									{% endfor %}
									<b>{{ child.name }}</b>
									{% if not loop.last or not loop.parent.loop.last %}<br />{% endif %}
								{% endfor %}
							{% endfor %}
						{% else %}
							The loadout <b>{{ loadout.name }}</b> will be deleted permanently.
						{% endif %}
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col">
				{{ form_start(form) }}
				{{ form_rest(form) }}
				<button type="submit" class="btn btn-danger">Delete above loadouts</button>
				{{ form_end(form) }}
			</div>
		</div>
	</div>
{% endblock %}

templates/default/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<div class="container">
		<div class="row">
			<div class="col-12">
				{% if is_granted('ROLE_USER') %}
					<div class="row">
						<div class="col">
							<div class="alert alert-info">
								<i class="fas fa-info-circle"></i>
								Welcome! To use this tool, either create a base materia loadout or click "Add example base loadout" to add a copy of an example.<br />
								Latest changes:<br />
								<ul>
									<li>Added drag/drop support for materias</li>
									<li>Added selection of which party member the cursor is on (if you open the materia loadout screen from their item view)</li>
									<li>Beta: Added automatic routing of materias. Pin materias that should not be moved for that mode.</li>
								</ul>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col">
							{% for ml in loadouts|filter(m => m.parent is same as(null)) %}
								<p><a href="{{ path('default_view_loadout', {loadout: ml.id}) }}">{{ ml.name }}</a></p>
							{% endfor %}
							<p>
								{{ form_start(demoform) }}
								<a href="{{ path('default_add_loadout') }}" class="btn btn-primary">Add new base materia loadout</a>
								<button type="submit" class="btn btn-outline-secondary">Add example base loadout</button>
								{{ form_end(demoform) }}
							</p>
						</div>
					</div>
				{% else %}
					<a href="{{ path('default_login') }}">Login with Twitch</a>
				{% endif %}
			</div>
		</div>
	</div>
{% endblock %}

templates/default/view.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<div class="row">
		<div class="col">
			<h1>
				Loadout {{ loadout.name }}
				{#FIXME add icons#}
				<a href="{{ path('default_edit_loadout', {loadout: loadout.id}) }}" class="btn btn-link">Edit</a>
			</h1>
		</div>
		<div class="col-auto">
			<div class="row">
				<div class="col-auto">
					<a href="{{ path('default_delete_loadout', {loadout: loadout.id}) }}" class="btn btn-danger">Delete loadout</a>
				</div>
				<div class="col-auto">
					<a href="{{ path('default_auto_loadout', {loadout: loadout.root.id}) }}" class="btn btn-info">View auto routing</a>
				</div>
				<div class="col-auto">
					{{ form_start(clone) }}
					<button type="submit" class="btn btn-outline-primary">Create changes from this loadout</button>
					{{ form_end(clone) }}
				</div>
			</div>
		</div>
	</div>

	<hr />

	<style>
		table tbody tr td {
			width: calc(100% / 7) !important;
		}
	</style>
	<div class="row">
		<div class="col-12 col-md-3 col-sm-4">
			<div id="sidebar" data-fav="{{ loadout.preferredChangeKey|default }}"></div>
		</div>
		<div class="col-12 col-md-9 col-sm-8">
			<div class="row mb-3">
				<div class="col">
					{% if loadout.parent|default %}
						<a class="btn btn-outline-primary" href="{{ path('default_view_loadout', {loadout: loadout.parent.id}) }}">Go to parent: {{ loadout.parent.name }}</a>
					{% endif %}
				</div>
				<div class="col-auto">
					{% for child in loadout.children %}
						<a class="btn btn-outline-primary" href="{{ path('default_view_loadout', {loadout: child.id}) }}">Go to child: {{ child.name }}</a>
					{% endfor %}
				</div>
			</div>
			<div id="table" data-id="{{ loadout.id }}">

			</div>

			<div class="row">
				<div class="col">
					<span class="small font-italic">Click any materia/empty slot to edit. Drag/drop cells onto other cells to swap them.</span>
				</div>
			</div>
		</div>
	</div>
	<meta name="materia-preference" content="{{ app.user.materiaCoordinatesPreference }}" />
{% endblock %}

{% block javascripts %}
	{{ parent() }}
	{{ encore_entry_script_tags('table') }}
{% endblock %}